### ISSUE TITLE
Linebreak in title and authors

### ISSUE THREAD

**Issue by raphaelsaavedra** [JuliaCon/JuliaConSubmission.jl#10]
Is it possible to add a linebreak in the title or authors? My title currently looks like this:

![image](https://user-images.githubusercontent.com/29098169/60125764-db19c880-9762-11e9-81c1-82313c010201.png)

So the first line is very long and the second very short, not to mention the start of the title is slightly overlapping with the JuliaCon logo. If it was pure .tex, I could just add `\\` afer "for" to get the following:

![image](https://user-images.githubusercontent.com/29098169/60125870-1c11dd00-9763-11e9-8a1d-62164fce0da2.png)

Which looks much better. I tried to do this in the .yml and it just doesn't work. One of my colleagues is also having a related issue where the name of one of the authors is split between two lines.

So, is there any way to add a linebreak in the .yml?

**Comment by andrewrosemberg** [comment]
I'm also having the same problem! The last name of one of my coauthors is separated from the rest of his name.

**Comment by matbesancon** [comment]
hi both, I tried and adding `//` after the author name before which you want to break seems to work (at least locally):
```
authors:
  - name: 1st author
    orcid: 0000-0003-1361-440X
    affiliation: 1
  - name: 2nd author
    affiliation: 1, 2
  - name: \\3rd author
    affiliation: 2
```

It does look a bit awkward but manageable
